In [2]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("C:/Users/Om Soni/OneDrive/Desktop/Sales_analytical_api/Data/sales.csv")

In [7]:
data.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Region,Quantity,Unit_Price,Discount,Sales,Cost,Profit
0,ORD102462,2025-01-01,CUST1056,Customer 1056,Pen Set,Stationery,Central,1,190.0,0.15,161.5,152.27,9.23
1,ORD102291,2025-01-01,CUST0206,Customer 0206,Keyboard,Electronics,East,1,2080.0,0.20,1664.0,1647.15,16.85
2,ORD103288,2025-01-01,CUST0625,Customer 0625,Monitor,Electronics,North,3,14390.0,0.15,36694.5,35204.07,1490.43
3,ORD101447,2025-01-01,CUST0170,Customer 0170,Pen Set,Stationery,North,1,190.0,0.00,190.0,150.98,39.02
4,ORD101320,2025-01-01,CUST0276,Customer 0276,Desk,Furniture,Central,4,12790.0,0.10,46044.0,35198.72,10845.28

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       5000 non-null   object
 1   Order_Date     5000 non-null   object
 2   Customer_ID    5000 non-null   object
 3   Customer_Name  5000 non-null   object
 4   Product        5000 non-null   object
 5   Category       5000 non-null   object
 6   Region         5000 non-null   object
 7   Quantity       5000 non-null   int64
 8   Unit_Price     5000 non-null   float64
 9   Discount       5000 non-null   float64
 10  Sales          5000 non-null   float64
 11  Cost           5000 non-null   float64
 12  Profit         5000 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 507.9+ KB

In [9]:
data.describe()

,Quantity,Unit_Price,Discount,Sales,Cost,Profit
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,3.178800,11237.250000,0.065170,33443.710200,24387.945016,9055.765184
std,2.196405,15812.949227,0.060142,61152.316873,44323.426436,18388.670033
min,1.000000,170.000000,0.000000,136.000000,93.980000,-770.620000
25%,1.000000,1660.000000,0.000000,2839.000000,2009.690000,598.282500
50%,3.000000,3760.000000,0.050000,10080.000000,7345.735000,2463.250000
75%,4.000000,12950.000000,0.100000,35468.000000,25605.222500,8846.417500
max,10.000000,59400.000000,0.200000,592600.000000,438613.260000,216171.380000

In [10]:
data.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Product          0
Category         0
Region           0
Quantity         0
Unit_Price       0
Discount         0
Sales            0
Cost             0
Profit           0
dtype: int64

In [11]:
data.isnull().sum().sum()

0

In [15]:
data.duplicated().sum()

0

In [18]:
data['Order_ID'].duplicated().sum()

0

In [19]:
data['Product'].value_counts()

Product
Laptop          453
Pen Set         440
Headphones      434
Keyboard        432
Office Chair    421
Mouse           420
Backpack        417
Monitor         406
Webcam          403
Smartphone      402
Desk            394
Notebook        378
Name: count, dtype: int64

In [20]:
data['Product'].unique()

array(['Pen Set', 'Keyboard', 'Monitor', 'Desk', 'Laptop', 'Backpack',
       'Webcam', 'Mouse', 'Smartphone', 'Headphones', 'Notebook',
       'Office Chair'], dtype=object)

In [21]:
data['Product'].nunique()

12

In [22]:
data['Category'].unique()

array(['Stationery', 'Electronics', 'Furniture', 'Accessories'],
      dtype=object)

In [23]:
data['Region'].unique()

array(['Central', 'East', 'North', 'West', 'South'], dtype=object)

In [24]:
"""
Creating KPI layer

Total Sales": total_sales,
    "Total Cost": total_cost,
    "Total Profit": total_profit,
    "Profit Margin %": profit_margin,
    "Total Units Sold": total_units,
    "Total Orders": total_orders,
    "Total Customers": total_customers
    """

'\nCreating KPI layer\n\nTotal Sales": total_sales,\n    "Total Cost": total_cost,\n    "Total Profit": total_profit,\n    "Profit Margin %": profit_margin,\n    "Total Units Sold": total_units,\n    "Total Orders": total_orders,\n    "Total Customers": total_customers\n    '

In [25]:
Total_sale = sum(data['Sales'])

In [26]:
Total_profit= sum(data['Profit'])

In [42]:
Profit_margin= (Total_profit / Total_sale) * 100

In [36]:
Total_Units_Sold = sum(data['Quantity'])

In [ ]:
data.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Region,Quantity,Unit_Price,Discount,Sales,Cost,Profit
0,ORD102462,2025-01-01,CUST1056,Customer 1056,Pen Set,Stationery,Central,1,190.0,0.15,161.5,152.27,9.23
1,ORD102291,2025-01-01,CUST0206,Customer 0206,Keyboard,Electronics,East,1,2080.0,0.20,1664.0,1647.15,16.85
2,ORD103288,2025-01-01,CUST0625,Customer 0625,Monitor,Electronics,North,3,14390.0,0.15,36694.5,35204.07,1490.43
3,ORD101447,2025-01-01,CUST0170,Customer 0170,Pen Set,Stationery,North,1,190.0,0.00,190.0,150.98,39.02
4,ORD101320,2025-01-01,CUST0276,Customer 0276,Desk,Furniture,Central,4,12790.0,0.10,46044.0,35198.72,10845.28

In [38]:
Total_order = data['Order_ID'].nunique()
Total_order

5000

In [39]:
Total_Customers = data['Customer_ID'].nunique()

In [43]:
# Then create ONE KPI summary

kpi = {
    "Total Sales" : Total_sale,
    "Total_Profit" : Total_profit,
    "Profit Margin %" : Profit_margin,
    "Total Unit Ordered" : Total_Units_Sold,
    "Total Order" : Total_order,
    "Total Customers" : Total_Customers
    
}

In [44]:
kpi

{'Total Sales': 167218551.0,
 'Total_Profit': 45278825.92,
 'Profit Margin %': 27.07763322264406,
 'Total Unit Ordered': 15894,
 'Total Order': 5000,
 'Total Customers': 1182}

In [ ]:
"""

Now let's make our KPI output professional
Instead of a dictionary, let's create a proper DataFrame:

"""

"Now let's make our KPI output professional\nInstead of a dictionary, let's create a proper DataFrame:"

In [47]:
Kpi = pd.DataFrame(kpi, index=[0])

In [50]:
Kpi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Total Sales         1 non-null      float64
 1   Total_Profit        1 non-null      float64
 2   Profit Margin %     1 non-null      float64
 3   Total Unit Ordered  1 non-null      int64
 4   Total Order         1 non-null      int64
 5   Total Customers     1 non-null      int64
dtypes: float64(3), int64(3)
memory usage: 56.0 bytes

In [51]:
Kpi

,Total Sales,Total_Profit,Profit Margin %,Total Unit Ordered,Total Order,Total Customers
0,167218551.0,45278825.92,27.077633,15894,5000,1182

In [52]:
kpi['Total Unit Sold']=kpi['Total Unit Ordered']

In [53]:
Kpi

,Total Sales,Total_Profit,Profit Margin %,Total Unit Ordered,Total Order,Total Customers
0,167218551.0,45278825.92,27.077633,15894,5000,1182

In [54]:
Kpi['Total Orders']=Kpi['Total Order']